Добавить обработку команды Add  event
Valentina810/week-planner-for-marusia pull request #46
Opened 2024-01-10 20:47 UTC by Valentina810

2024-01-10 20:57 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/storage/session/SessionStorage.java
>      public void calculatePrevActions(Object object) {
[  ] К getActionsStorage() который чуть выше: здесь нарушается принцип KISS (Keep It Simple, Stupid). Множественные вызовы Gson создают избыточный код. Лучше

private ActionsStorage getActionsStorage() {
    return Optional.ofNullable(session_state)
            .map(obj -> new Gson().fromJson(new Gson().toJson(obj), ActionsStorage.class))
            .orElse(ACTIONS_STORAGE_EMPTY);
}

2024-01-10 21:08 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/ActionExecutor.java
- [] К методу getPhrase: вместо использования регулярных выражений, можно использовать библиотеки для обработки текста:

```java
private String getPhrase(String message) {
    return StringUtils.isNotBlank(message) ?
            message.replaceAll("[^а-яА-Я0-9\\s]", "").toLowerCase() : "";
}
```

2024-01-11 19:49 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/CommandLoader.java
> -    public Loader() {
- [ ] Вместо использования цикла forEach и создания временной коллекции можно применить стримы и функциональные интерфейсы

```java
this.loadCommands = FileReader.loadJsonFromFile("dictionary.json")
        .stream()
        .map(json -> new Gson().fromJson(new Gson().toJson(json), Command.class))
        .collect(Collectors.toMap(e -> e.getPhrase().toLowerCase(), Function.identity()));
```

2024-01-11 19:53 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/CommandLoader.java
> +    public CommandLoader() {
- [ ] Нарушение принципа DRY одинаковая логика для создания Command повторяется

```java
public CommandLoader() {
    this.loadCommands = FileReader.loadJsonFromFile("dictionary.json")
            .stream()
            .map(json -> new Gson().fromJson(new Gson().toJson(json), Command.class))
            .collect(Collectors.toMap(e -> e.getPhrase().toLowerCase(), Function.identity()));
}
```

2024-01-11 19:55 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/CommandLoader.java
> +    public Command get(String phrase) {
- [ ] Вместо использования тернарного оператора можно применить паттерн Null Object

```java
public Command get(String phrase) {
    return loadCommands.getOrDefault(phrase, loadCommands.get("custom"));
}
```

2024-01-12 18:11 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/HandlerFactory.java
> +    public SimpleHandler getHandler(Command command) {
- [ ] Здесь нарушается принцип открытости/закрытости (O из SOLID), так как при добавлении нового типа обработчика придется модифицировать этот метод, как вариант:

```java
public interface HandlerFactory {
    SimpleHandler createHandler(ParametersHandler parametersHandler);
}

public class SimpleHandlerFactory implements HandlerFactory {
    public SimpleHandler createHandler(ParametersHandler parametersHandler) {
        return new SimpleHandler(parametersHandler);
    }
}

public class CompositeHandlerFactory implements HandlerFactory {
    private final Map<TypeAction, BaseCompositeExecutor> baseExecutors;

    public CompositeHandlerFactory(Map<TypeAction, BaseCompositeExecutor> baseExecutors) {
        this.baseExecutors = baseExecutors;
    }

    public SimpleHandler createHandler(ParametersHandler parametersHandler) {
        BaseCompositeExecutor baseCompositeExecutor = baseExecutors.get(parametersHandler.getCommand().getOperation());
        return baseCompositeExecutor == null ? new CompositeHandler(parametersHandler, baseExecutors.get(TypeAction.UNKNOWN).getActionExecute()) :
                new CompositeHandler(parametersHandler, baseCompositeExecutor.getActionExecute());
    }
}
```

2024-01-12 18:21 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/composite/BaseCompositeExecutor.java
>                                      .collect(Collectors.joining(" ")))
- [] К строке 40: Обработка NullPointerException не является хорошей практикой. Лучше проверять на null перед использованием объекта и обрабатывать эту ситуацию соответствующим образом.

2024-01-12 18:24 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/composite/WeeklyPlanCompositeExecutor.java
>                          .getWeek().getDays().stream()
- [ ] В этом коде присутствует потенциальная проблема с возможным NullPointerException, если какой-то из вызываемых методов вернёт null. 
Для предотвращения возможного NullPointerException можно использовать Optional, например:

```java
days = Optional.ofNullable(parHandler.getPersistentStorage())
                .map(PersistentStorage::getWeekStorage)
                .map(WeekStorage::getWeek)
                .map(Week::getDays)
                .orElse(Collections.emptyList())
                .stream()
                .filter(e -> !e.getEvents().isEmpty())
                .collect(Collectors.toList());
```

2024-01-12 18:32 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/composite/BaseCompositeExecutor.java
>              List<Day> events = parametersHandler.getPersistentStorage().getWeekStorage().getWeek().getDays().stream()
- [ ] Здесь возможно нарушение принципа Law of Demeter, так как происходит обращение к вложенным объектам. Это может быть признаком того, что объект ParametersHandler имеет слишком много ответственностей.
Вариант улучшения: Рефакторинг класса ParametersHandler, чтобы уменьшить его ответственности.

2024-01-15 19:20 UTC, AndrewNocode requested changes
Есть критичные замечания, надо поправить

2024-01-15 19:20 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/template/SimpleHandler.java
>      /**
- [ ] Каждый метод должен отвечать за одну функциональность. В данном случае метод отвечает за установку параметров, инициализацию и установку SessionStorage и PersistentStorage. Вариант:

```java
void setDefaultValueParameters(ParametersHandler parameters) {
        parameters.setIsEndSession(false);
        setSessionStorage(parameters);
        setPersistentStorage(parameters);
    }

void setSessionStorage(ParametersHandler parameters) {
        SessionStorage sessionStorage = new SessionStorage();
        sessionStorage.calculatePrevActions(parameters.getUserRequest().getState().getSession());
        parameters.setSessionStorage(sessionStorage);
}

void setPersistentStorage(ParametersHandler parameters) {
        PersistentStorage persistentStorage = new PersistentStorage();
        persistentStorage.getWeekEvents(parameters.getUserRequest().getState().getUser());
        parameters.setPersistentStorage(persistentStorage);
}
```

2024-01-15 19:20 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/storage/session/SessionStorage.java
>      public void addAction(PrevAction prevAction) {
- [ ] Метод addAction выполняет несколько действий: он получает хранилище действий, добавляет новое действие и затем устанавливает обновленные действия. 
    Вариант улучшения:

```java
public void addAction(PrevAction prevAction) {
        addPrevActionToStorage(prevAction);
        updateActions();
    }

    private void addPrevActionToStorage(PrevAction prevAction) {
        ActionsStorage actionsStorage = getActionsStorage();
        actionsStorage.getActions().getPrevActions().add(prevAction);
    }

    private void updateActions() {
        setActions(getActionsStorage().getActions());
    }
```

2024-01-17 18:36 UTC, Valentina810 commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/HandlerFactory.java
> +    public SimpleHandler getHandler(Command command) {
Здесь пока без изменений, как будет третий тип обработчика, разнесем по классам

2024-01-17 18:39 UTC, Valentina810 commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/HandlerFactory.java
> +        ParametersHandler parametersHandler = ParametersHandler.builder().command(command).build();
Подумаю еще как переписать createHandler() - не нравится

2024-01-17 18:56 UTC, Valentina810 commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/composite/BaseCompositeExecutor.java
>              List<Day> events = parametersHandler.getPersistentStorage().getWeekStorage().getWeek().getDays().stream()
В PersistentStorage добавлен метод для получения массива дней с событиями

2024-01-25 21:58 UTC, Valentina810 commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/handler/ParametersHandler.java
>  public class ParametersHandler {
- [ ] подумать как разбить класс на более мелкие

2024-02-08 21:14 UTC, merged