Добавить тесты
Valentina810/week-planner-for-marusia pull request #48
Opened 2024-02-11 22:20 UTC by Valentina810

2024-02-14 21:32 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/integration/action/TodayPlanHandlerTest.java
> +    private WeekPlannerService weekPlannerService;
Все тесты в этом пакете должны быть на сервис, отдельно тесты на классы с Моками

2024-02-14 21:33 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/integration/action/TodayPlanHandlerTest.java
> +    private WeekPlannerService weekPlannerService;
🥳🥳🥳

2024-02-14 21:45 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/integration/action/TodayPlanHandlerTest.java
> +        assertEquals(parameterForEventsForDateTest.getExpectedResult(),
- [ ] Добавить проверки состояний хранилищ и свойства isEndSession. Во всех тестах этого пакета

2024-02-14 21:47 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/integration/action/TodayPlanHandlerTest.java
>  package com.github.valentina810.weekplannerformarusia.integration.action;
- [ ] Пакет переименовать в service

2024-02-21 18:42 UTC, AndrewNocode requested changes

2024-02-21 18:42 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/WeeklyPlanExecutor.java
>                                          .map(event -> " " + event.getName() + " " + event.getTime())
- [ ] Сортировку по времени внутри дня тоже сразу можно сделать

2024-02-22 19:24 UTC, Valentina810 commented on src/main/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/WeeklyPlanExecutor.java
>                                          .map(event -> " " + event.getName() + " " + event.getTime())
Добавила

2024-03-10 19:47 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/integration/action/TodayPlanHandlerTest.java
> +        assertEquals(parameterForEventsForDateTest.getExpectedResult(),
готово 🥳🥳🥳

2024-03-16 23:29 UTC, AndrewNocode commented on src/main/java/com/github/valentina810/weekplannerformarusia/dto/ResponseParameters.java
> +    @Setter
🥞

2024-03-17 16:22 UTC, AndrewNocode approved these changes

2024-03-17 16:23 UTC, merged