Добавить дополнительные тесты
Valentina810/week-planner-for-marusia pull request #50
Opened 2024-03-17 20:29 UTC by Valentina810

2024-03-17 23:09 UTC, AndrewNocode requested changes

2024-03-17 23:09 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/controller/WeekPlannerControllerTest.java
> +class WeekPlannerControllerTest {
- [ ] +сервис

2024-03-17 23:10 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/controller/WeekPlannerControllerTest.java
> +class WeekPlannerControllerTest {
🫡

2024-03-21 16:29 UTC, AndrewNocode requested changes

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/exception/ErrorHandlerTest.java
> +        openMocks(this);
- [ ] В этом классе нет моков

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
> +        openMocks(this);
- [ ] Аналогично, тут нет моков, если будут - вынести в аннотацию

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/exception/ErrorHandlerTest.java
> +        assertEquals("/webhook", errorResponse.getPath());
- [ ] Можно использовать MockMvc для проверки пути

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/exception/ErrorHandlerTest.java
> +        RuntimeException runtimeException = new RuntimeException("Сообщение");
- [ ] Строки 24 и 25 - повторяющийся код, во втором тесте то же самое, лучше вынести в @BeforeEach

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
> +        Week week = Week.builder().build();
- [ ] Week нужно сделать моком

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
> +        Event event = new Event(EVENT_TIME_FOR_TIME, EVENT_NAME);
- [ ] Неплохо бы добавить тест с неправильным временем

2024-03-21 16:29 UTC, AndrewNocode commented on src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
> +        Event event = new Event(EVENT_TIME_FOR_TIME, EVENT_NAME);
- [ ] Тоже можно заменить моком

2024-03-21 19:02 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
> +        Week week = Week.builder().build();
Поведение не проверяется, нет смысла, но оптимизировано, убрано дублирование

2024-03-21 19:16 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
> +        Event event = new Event(EVENT_TIME_FOR_TIME, EVENT_NAME);
добавлен

2024-03-24 17:13 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/exception/ErrorHandlerTest.java
> +        assertEquals("/webhook", errorResponse.getPath());
Это проверяется в другом тесте, класс WeekPlannerControllerTest, строка 85

2024-03-24 17:13 UTC, Valentina810 commented on src/test/java/com/github/valentina810/weekplannerformarusia/exception/ErrorHandlerTest.java
> +        RuntimeException runtimeException = new RuntimeException("Сообщение");
Объединено в один тест

2024-03-24 17:14 UTC, Valentina810 commented
Готово @AndrewNocode

2024-03-24 17:15 UTC, AndrewNocode approved these changes

2024-03-24 17:16 UTC, merged